events { 
    worker_connections 1024; 
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Настройка для работы WebSockets (нужно для SignalR)
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    # Rate Limits
    limit_req_zone $binary_remote_addr zone=api_limit_zone:10m rate=50r/s;

    server {
        listen 80;
        listen [::]:80;
        
        # Шлюз отвечает просто на localhost
        server_name localhost;

        # Проксирование запросов к бэкенду API 
        location /api/ {
            limit_req zone=api_limit_zone nodelay;
            limit_req_status 429; # Выдаем 429 Too Many Requests при спаме

            proxy_pass http://orbitx:8080; 
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Проксирование веб-сокетов SignalR
        location /ws/satellite {
            proxy_pass http://orbitx:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Проксирование всех остальных запросов на локальный фронтенд Vue
        location / {
            proxy_pass http://orbitx.frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Роутинг для локальной отладки кастомной 404 страницы во Vue
            proxy_intercept_errors on;
            error_page 404 =200 /index.html;
        }
    }
}
