// <auto-generated />
using System;
using Core.Modules.SatelliteData.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Modules.SatelliteData.Domain.Infrastructure.Migrations
{
    [DbContext(typeof(OMMDBContext))]
    partial class TLEDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Modules.SatelliteData.Domain.Models.Satellite", b =>
                {
                    b.Property<int>("NORAD_CAT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NORAD_CAT_ID"));

                    b.Property<double>("ARG_OF_PERICENTER")
                        .HasColumnType("double precision");

                    b.Property<double>("BSTAR")
                        .HasColumnType("double precision");

                    b.Property<string>("CLASSIFICATION_TYPE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ECCENTRICITY")
                        .HasColumnType("double precision");

                    b.Property<int>("ELEMENT_SET_NO")
                        .HasColumnType("integer");

                    b.Property<int>("EPHEMERIS_TYPE")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EPOCH")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("INCLINATION")
                        .HasColumnType("double precision");

                    b.Property<double>("MEAN_ANOMALY")
                        .HasColumnType("double precision");

                    b.Property<double>("MEAN_MOTION")
                        .HasColumnType("double precision");

                    b.Property<double>("MEAN_MOTION_DDOT")
                        .HasColumnType("double precision");

                    b.Property<double>("MEAN_MOTION_DOT")
                        .HasColumnType("double precision");

                    b.Property<string>("OBJECT_ID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OBJECT_NAME")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RA_OF_ASC_NODE")
                        .HasColumnType("double precision");

                    b.Property<int>("REV_AT_EPOCH")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NORAD_CAT_ID");

                    b.HasIndex("Category");

                    b.ToTable("Satellites", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
